name: textbooks
favicon: null
layout_spectrum: 0.858225422911346
typography_spectrum: 0.5477453479543328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.9124006652273238
purpose:
  - name: follow
    item: null
    url: null
